# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/samdoiron/Code/Jeshim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/samdoiron/Code/Jeshim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/samdoiron/Code/Jeshim/CMakeFiles /Users/samdoiron/Code/Jeshim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/samdoiron/Code/Jeshim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jeshim

# Build rule for target.
jeshim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jeshim
.PHONY : jeshim

# fast build rule for target.
jeshim/fast:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/build
.PHONY : jeshim/fast

dimensions.o: dimensions.cc.o
.PHONY : dimensions.o

# target to build an object file
dimensions.cc.o:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/dimensions.cc.o
.PHONY : dimensions.cc.o

dimensions.i: dimensions.cc.i
.PHONY : dimensions.i

# target to preprocess a source file
dimensions.cc.i:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/dimensions.cc.i
.PHONY : dimensions.cc.i

dimensions.s: dimensions.cc.s
.PHONY : dimensions.s

# target to generate assembly for a file
dimensions.cc.s:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/dimensions.cc.s
.PHONY : dimensions.cc.s

entity.o: entity.cc.o
.PHONY : entity.o

# target to build an object file
entity.cc.o:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/entity.cc.o
.PHONY : entity.cc.o

entity.i: entity.cc.i
.PHONY : entity.i

# target to preprocess a source file
entity.cc.i:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/entity.cc.i
.PHONY : entity.cc.i

entity.s: entity.cc.s
.PHONY : entity.s

# target to generate assembly for a file
entity.cc.s:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/entity.cc.s
.PHONY : entity.cc.s

jeshim.o: jeshim.cc.o
.PHONY : jeshim.o

# target to build an object file
jeshim.cc.o:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/jeshim.cc.o
.PHONY : jeshim.cc.o

jeshim.i: jeshim.cc.i
.PHONY : jeshim.i

# target to preprocess a source file
jeshim.cc.i:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/jeshim.cc.i
.PHONY : jeshim.cc.i

jeshim.s: jeshim.cc.s
.PHONY : jeshim.s

# target to generate assembly for a file
jeshim.cc.s:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/jeshim.cc.s
.PHONY : jeshim.cc.s

point.o: point.cc.o
.PHONY : point.o

# target to build an object file
point.cc.o:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/point.cc.o
.PHONY : point.cc.o

point.i: point.cc.i
.PHONY : point.i

# target to preprocess a source file
point.cc.i:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/point.cc.i
.PHONY : point.cc.i

point.s: point.cc.s
.PHONY : point.s

# target to generate assembly for a file
point.cc.s:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/point.cc.s
.PHONY : point.cc.s

rendersurface.o: rendersurface.cc.o
.PHONY : rendersurface.o

# target to build an object file
rendersurface.cc.o:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/rendersurface.cc.o
.PHONY : rendersurface.cc.o

rendersurface.i: rendersurface.cc.i
.PHONY : rendersurface.i

# target to preprocess a source file
rendersurface.cc.i:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/rendersurface.cc.i
.PHONY : rendersurface.cc.i

rendersurface.s: rendersurface.cc.s
.PHONY : rendersurface.s

# target to generate assembly for a file
rendersurface.cc.s:
	$(MAKE) -f CMakeFiles/jeshim.dir/build.make CMakeFiles/jeshim.dir/rendersurface.cc.s
.PHONY : rendersurface.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... jeshim"
	@echo "... rebuild_cache"
	@echo "... dimensions.o"
	@echo "... dimensions.i"
	@echo "... dimensions.s"
	@echo "... entity.o"
	@echo "... entity.i"
	@echo "... entity.s"
	@echo "... jeshim.o"
	@echo "... jeshim.i"
	@echo "... jeshim.s"
	@echo "... point.o"
	@echo "... point.i"
	@echo "... point.s"
	@echo "... rendersurface.o"
	@echo "... rendersurface.i"
	@echo "... rendersurface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

